### ISSUE TITLE
General observations

### ISSUE THREAD

**Issue by SergeyBarskiy** [shawnwildermuth/CoreCodeCamp#1]
It worked for me, though I had to do it a few times.  The other note is that screen takes a few seconds to load, so I mistakenly hit call for speakers multiple times, and eventually the page loaded.  Once I hit enter key half way though the screen, and it cleared.  Maybe showing required fields via asterisk would help?  Showing some sort of loading indicator might help with page load times?  Not sure if this is what caused the problem.

**Comment by shawnwildermuth** [comment]
Trying to improve the Angular2 loading times. Not sure why it's so slow. I'll see what I can do. Thanks

**Comment by shawnwildermuth** [comment]
I've changed this to make it clearer the required fields and added loading icons to every angular app. I am also going to package all the .js once we get to release to speed up the angularJs loading.
