### ISSUE TITLE
Enable speakers to update session info after CFS closes.

### ISSUE THREAD

**Issue by pkskelly** [shawnwildermuth/CoreCodeCamp#12]
Had a speaker request to update the abstract information for a session, but since CFS is closed he cannot edit his talks. Logging an issue as feature request to enable editing session abstract information once the CFS is closed.

**Comment by shawnwildermuth** [comment]
Added new link when users are logged in to go to their speaker page. You could also point them at /{moniker}/CallForSpeakers/Speaker e.g. http://atlantacodecamp.com/2017/CallForSpeakers/Speaker
