### ISSUE TITLE
AdBlock Plus on Chrome causes the Sponsor tiles to be hidden

### ISSUE THREAD

**Issue by KeithJRome** [shawnwildermuth/CoreCodeCamp#13]
Simply disabling the extension for this page causes them to appear again. In other words - the Sponsor tiles look like ads to that plugin (and maybe other similar plugins).

**Comment by shawnwildermuth** [comment]
This has been an issue for the past five years. I'm open to suggestions, but don't know how to fix.

**Comment by shawnwildermuth** [comment]
Think I fixed it.
