### ISSUE TITLE
Clear Track, Room, Timeslot when removing a talk 

### ISSUE THREAD

**Issue by pkskelly** [shawnwildermuth/CoreCodeCamp#15]
When a speaker is removed (unapproved), the track, room and timeslot should be blanked out.  Or, the Track, Room an Timeslot should have a blank value enabled for resetting.  

This issue came up this year as speakers had to cancel sessions.

**Comment by shawnwildermuth** [comment]
If you change the item to "unapproved" it will stop showing up. Do I still need to clear the track, room and timeslot? I think leaving them is safer (in case you unapprove a talk by accident, it doesn't lose it's spot).

**Comment by pkskelly** [comment]
Since "unapproving" now removes them from the schedule, this is fine.   Leaving the room, etc. does seem safer in case of accidental unapprovals.  Thanks!
