### ISSUE TITLE
Did not receive confirmation email 

### ISSUE THREAD

**Issue by pkskelly** [shawnwildermuth/CoreCodeCamp#2]
Registered at 3:20pm today (7/10) and still have not received confirmation email (4:25p) to attempt to apply on CFP page.   Requested resend of email, still no luck.  Will keep an eye out for the email and update this issue.

**Comment by pkskelly** [comment]
Still no confirmation email.

**Comment by shawnwildermuth** [comment]
Thanks, i'll see why SendGrid isn't sending them. May just be a misconfiguration.

**Comment by shawnwildermuth** [comment]
Found out why, the settings were using an invalid from address (so SendGrid was rejecting the emails). It's fixed on the site now (no code change).
