### ISSUE TITLE
Relax password restrictions

### ISSUE THREAD

**Issue by jwooley** [shawnwildermuth/CoreCodeCamp#3]
We don't need complex password restrictions on the site. Consider relaxing/removing the complexity restriction. Also, not sure if 2 factor auth is really necessary for our purposes.

**Comment by shawnwildermuth** [comment]
I relaxed the password requirements and show the requirements when you register. I think the one-time validation of the email will guarantee that we have good emails for the speakers, but I'm open to being talked out of it.

**Comment by jwooley** [comment]
Thanks shawn. My argument against the email validation is because of the other issue where emails are not being received. (I never got mine FWIW)

**Comment by shawnwildermuth** [comment]
did you try again?
