### ISSUE TITLE
Shirt size options.

### ISSUE THREAD

**Issue by CANUSA** [shawnwildermuth/CoreCodeCamp#4]
I think we need a few more on the large end, we only go up to 2x.

**Comment by shawnwildermuth** [comment]
How big can we go?  Tell me what sizes we need and can go up to?

**Comment by CANUSA** [comment]
I don't know, but at SPS we had a few folks who were 4x. also, do we need to specify women's cuts?

**Comment by shawnwildermuth** [comment]
Your call. Let's talk about it Monday. It's an easy addition.

**Comment by shawnwildermuth** [comment]
Do we have an answer to t-shirt sizes yet?

**Comment by shawnwildermuth** [comment]
How big can shirts go?
