### ISSUE TITLE
Save button on Speaker Info page

### ISSUE THREAD

**Issue by KeithJRome** [shawnwildermuth/CoreCodeCamp#8]
When editing my own speaker information (at /2017/CallForSpeakers/Speaker#/edit), clicking the Save button does not seem to do anything. This is an existing speaker entry, not a new one.

I noticed that t-shirt size was not selected (and is a required field), but even after selecting a value and saving, it still does not reflect any changes when I go back to view the data (at /2017/CallForSpeakers/Speaker#/info).

The Save button becomes disabled after pressing (I guess this means that the page *thinks* it has been saved). But no error message or confirmation of save is shown.

**Comment by shawnwildermuth** [comment]
I'll take a look.
